// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr5VyKQZlIFeKdqU22_hKmCxk0qOvJHFY',
    appId: '1:1082176046719:web:aaae912b440b9bd26ce14a',
    messagingSenderId: '1082176046719',
    projectId: 'chat-d33e1',
    authDomain: 'chat-d33e1.firebaseapp.com',
    storageBucket: 'chat-d33e1.appspot.com',
    measurementId: 'G-1KTJRF5PW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8CdtaTsaD9KzQEIxJ0Ow7OQj58L_JfFg',
    appId: '1:1082176046719:android:d426af2c6f339ff26ce14a',
    messagingSenderId: '1082176046719',
    projectId: 'chat-d33e1',
    storageBucket: 'chat-d33e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQG1IxIOtJPpnoQ8IeKiv3xf7YFtApXM',
    appId: '1:1082176046719:ios:ddc4c62906fd8ae96ce14a',
    messagingSenderId: '1082176046719',
    projectId: 'chat-d33e1',
    storageBucket: 'chat-d33e1.appspot.com',
    iosClientId: '1082176046719-go2sqccggatgqstk7t7okivvba3722sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatz',
  );
}
